services:
  app_proxy:
    environment:
      APP_HOST: pubky-node_server_1
      APP_PORT: 9090

  server:
    image: ghcr.io/pubky/pubky-node:v0.2.0
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - RUST_LOG=pubky_node=info,pkarr=info
      - PUBKY_DNS_ENABLED=false
